server:
  port: 8888

spring:
  datasource:
    name: datasource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/book?serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      time-between-eviction-runs-millis: 300000
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
